// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: WaveSentinel

#include "../ui.h"

void ui_scrCC1101Stuff_screen_init(void)
{
    ui_scrCC1101Stuff = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrCC1101Stuff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrCC1101Stuff, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrCC1101Stuff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_scrCC1101Stuff, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCC1101Scan = lv_label_create(ui_scrCC1101Stuff);
    lv_obj_set_width(ui_lblCC1101Scan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCC1101Scan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCC1101Scan, 0);
    lv_obj_set_y(ui_lblCC1101Scan, -223);
    lv_obj_set_align(ui_lblCC1101Scan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCC1101Scan, "CC1101 STUFF");
    lv_obj_set_style_text_color(ui_lblCC1101Scan, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCC1101Scan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCC1101Scan, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tabCC1101Stuff = lv_tabview_create(ui_scrCC1101Stuff, LV_DIR_BOTTOM, 30);
    lv_obj_set_width(ui_tabCC1101Stuff, 320);
    lv_obj_set_height(ui_tabCC1101Stuff, 365);
    lv_obj_set_x(ui_tabCC1101Stuff, 0);
    lv_obj_set_y(ui_tabCC1101Stuff, -23);
    lv_obj_set_align(ui_tabCC1101Stuff, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tabCC1101Stuff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tabCC1101Stuff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tabCC1101Stuff, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_tabCC1101Stuff), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_tabCC1101Stuff), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_tabCC1101Stuff), lv_color_hex(0xFF9202),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_tabCC1101Stuff), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_tabCC1101Stuff), &ui_font_Verdana11,
                               LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Scanner = lv_tabview_add_tab(ui_tabCC1101Stuff, "SCANNER");

    ui_txtScannerData = lv_textarea_create(ui_Scanner);
    lv_obj_set_width(ui_txtScannerData, 170);
    lv_obj_set_height(ui_txtScannerData, 153);
    lv_obj_set_x(ui_txtScannerData, -63);
    lv_obj_set_y(ui_txtScannerData, 68);
    lv_obj_set_align(ui_txtScannerData, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtScannerData, "Signals Marked...");
    lv_obj_set_style_text_color(ui_txtScannerData, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtScannerData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtScannerData, lv_color_hex(0x443BE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtScannerData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_txtScanStopFq = lv_textarea_create(ui_Scanner);
    lv_obj_set_width(ui_txtScanStopFq, 120);
    lv_obj_set_height(ui_txtScanStopFq, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_txtScanStopFq, -43);
    lv_obj_set_y(ui_txtScanStopFq, -83);
    lv_obj_set_align(ui_txtScanStopFq, LV_ALIGN_CENTER);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_txtScanStopFq, NULL);
    else lv_textarea_set_accepted_chars(ui_txtScanStopFq, "1234567890.");
    lv_textarea_set_max_length(ui_txtScanStopFq, 6);
    lv_textarea_set_text(ui_txtScanStopFq, "434.50");
    lv_textarea_set_one_line(ui_txtScanStopFq, true);
    lv_obj_set_style_text_color(ui_txtScanStopFq, lv_color_hex(0x00FFEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtScanStopFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtScanStopFq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtScanStopFq, &ui_font_LCD20at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtScanStopFq, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtScanStopFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_txtScanStartFq = lv_textarea_create(ui_Scanner);
    lv_obj_set_width(ui_txtScanStartFq, 120);
    lv_obj_set_height(ui_txtScanStartFq, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_txtScanStartFq, -43);
    lv_obj_set_y(ui_txtScanStartFq, -132);
    lv_obj_set_align(ui_txtScanStartFq, LV_ALIGN_CENTER);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_txtScanStartFq, NULL);
    else lv_textarea_set_accepted_chars(ui_txtScanStartFq, "1234567890.");
    lv_textarea_set_max_length(ui_txtScanStartFq, 6);
    lv_textarea_set_text(ui_txtScanStartFq, "433.50");
    lv_textarea_set_one_line(ui_txtScanStartFq, true);
    lv_obj_set_style_text_color(ui_txtScanStartFq, lv_color_hex(0x00FFEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtScanStartFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtScanStartFq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtScanStartFq, &ui_font_LCD20at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtScanStartFq, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtScanStartFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_lblScanStartFq = lv_label_create(ui_Scanner);
    lv_obj_set_width(ui_lblScanStartFq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScanStartFq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblScanStartFq, -133);
    lv_obj_set_y(ui_lblScanStartFq, -133);
    lv_obj_set_align(ui_lblScanStartFq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScanStartFq, "START\nMHZ");
    lv_obj_set_style_text_color(ui_lblScanStartFq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblScanStartFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblScanStartFq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblScanStopFq = lv_label_create(ui_Scanner);
    lv_obj_set_width(ui_lblScanStopFq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScanStopFq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblScanStopFq, -136);
    lv_obj_set_y(ui_lblScanStopFq, -84);
    lv_obj_set_align(ui_lblScanStopFq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScanStopFq, "STOP\nMHZ");
    lv_obj_set_style_text_color(ui_lblScanStopFq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblScanStopFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblScanStopFq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swScannerOn = lv_switch_create(ui_Scanner);
    lv_obj_set_width(ui_swScannerOn, 70);
    lv_obj_set_height(ui_swScannerOn, 26);
    lv_obj_set_x(ui_swScannerOn, 82);
    lv_obj_set_y(ui_swScannerOn, 74);
    lv_obj_set_align(ui_swScannerOn, LV_ALIGN_CENTER);


    ui_lblScanEnable = lv_label_create(ui_Scanner);
    lv_obj_set_width(ui_lblScanEnable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScanEnable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblScanEnable, 81);
    lv_obj_set_y(ui_lblScanEnable, 50);
    lv_obj_set_align(ui_lblScanEnable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScanEnable, "ON/OFF");
    lv_obj_set_style_text_color(ui_lblScanEnable, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblScanEnable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblScanEnable, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnScannerClear = lv_btn_create(ui_Scanner);
    lv_obj_set_width(ui_btnScannerClear, 70);
    lv_obj_set_height(ui_btnScannerClear, 27);
    lv_obj_set_x(ui_btnScannerClear, 83);
    lv_obj_set_y(ui_btnScannerClear, 117);
    lv_obj_set_align(ui_btnScannerClear, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnScannerClear, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnScannerClear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblScannerClear = lv_label_create(ui_btnScannerClear);
    lv_obj_set_width(ui_lblScannerClear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScannerClear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblScannerClear, -1);
    lv_obj_set_y(ui_lblScannerClear, 1);
    lv_obj_set_align(ui_lblScannerClear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScannerClear, "CLEAR");
    lv_obj_set_style_text_font(ui_lblScannerClear, &ui_font_Verdana16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sldThreshold = lv_slider_create(ui_Scanner);
    lv_slider_set_range(ui_sldThreshold, -80, -10);
    lv_slider_set_value(ui_sldThreshold, -74, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sldThreshold) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sldThreshold, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_sldThreshold, 252);
    lv_obj_set_height(ui_sldThreshold, 15);
    lv_obj_set_x(ui_sldThreshold, -23);
    lv_obj_set_y(ui_sldThreshold, -25);
    lv_obj_set_align(ui_sldThreshold, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_sldThreshold, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sldThreshold, lv_color_hex(0x7E7D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sldThreshold, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sldThreshold, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sldThreshold, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sldThreshold, lv_color_hex(0xFC9696), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sldThreshold, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sldThreshold, &ui_img_needle_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_sldThreshold, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_sldThreshold, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_sldThreshold, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblSldThreshold = lv_label_create(ui_Scanner);
    lv_obj_set_width(ui_lblSldThreshold, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSldThreshold, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSldThreshold, -90);
    lv_obj_set_y(ui_lblSldThreshold, -45);
    lv_obj_set_align(ui_lblSldThreshold, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSldThreshold, "RSSI THRESHOLD");
    lv_obj_set_style_text_color(ui_lblSldThreshold, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSldThreshold, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblThreshold = lv_label_create(ui_Scanner);
    lv_obj_set_width(ui_lblThreshold, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblThreshold, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblThreshold, 132);
    lv_obj_set_y(ui_lblThreshold, -25);
    lv_obj_set_align(ui_lblThreshold, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblThreshold, "-74");
    lv_obj_set_style_text_color(ui_lblThreshold, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblThreshold, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblThreshold, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddl1101ScanPreset = lv_dropdown_create(ui_Scanner);
    lv_dropdown_set_options(ui_ddl1101ScanPreset,
                            "< Manual\n300.00\n303.87\n304.25\n310.00\n315.00\n318.00\n390.00\n418.00\n433.07\n433.92\n434.42\n434.77\n438.90\n868.3\n868.35\n868.865\n868.95\n915.00\n925.00");
    lv_obj_set_width(ui_ddl1101ScanPreset, 102);
    lv_obj_set_height(ui_ddl1101ScanPreset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddl1101ScanPreset, 86);
    lv_obj_set_y(ui_ddl1101ScanPreset, -131);
    lv_obj_set_align(ui_ddl1101ScanPreset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ddl1101ScanPreset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_lbl1101ScanPreset = lv_label_create(ui_Scanner);
    lv_obj_set_width(ui_lbl1101ScanPreset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl1101ScanPreset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl1101ScanPreset, 84);
    lv_obj_set_y(ui_lbl1101ScanPreset, -101);
    lv_obj_set_align(ui_lbl1101ScanPreset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl1101ScanPreset, "Fq PRESET");
    lv_obj_set_style_text_color(ui_lbl1101ScanPreset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl1101ScanPreset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chkScanPresets = lv_checkbox_create(ui_Scanner);
    lv_checkbox_set_text(ui_chkScanPresets, "SCAN PRESETS");
    lv_obj_set_width(ui_chkScanPresets, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkScanPresets, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkScanPresets, 87);
    lv_obj_set_y(ui_chkScanPresets, -73);
    lv_obj_set_align(ui_chkScanPresets, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkScanPresets, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_chkScanPresets, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_color(ui_chkScanPresets, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chkScanPresets, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chkScanPresets, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Generator = lv_tabview_add_tab(ui_tabCC1101Stuff, "PACKET GEN");

    ui_txt1101GenFreq = lv_textarea_create(ui_Generator);
    lv_obj_set_width(ui_txt1101GenFreq, 120);
    lv_obj_set_height(ui_txt1101GenFreq, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_txt1101GenFreq, -43);
    lv_obj_set_y(ui_txt1101GenFreq, -132);
    lv_obj_set_align(ui_txt1101GenFreq, LV_ALIGN_CENTER);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_txt1101GenFreq, NULL);
    else lv_textarea_set_accepted_chars(ui_txt1101GenFreq, "1234567890.");
    lv_textarea_set_max_length(ui_txt1101GenFreq, 6);
    lv_textarea_set_text(ui_txt1101GenFreq, "433.50");
    lv_textarea_set_one_line(ui_txt1101GenFreq, true);
    lv_obj_set_style_text_color(ui_txt1101GenFreq, lv_color_hex(0x00FFEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txt1101GenFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txt1101GenFreq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txt1101GenFreq, &ui_font_LCD20at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txt1101GenFreq, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txt1101GenFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_swGenEnable = lv_switch_create(ui_Generator);
    lv_obj_set_width(ui_swGenEnable, 65);
    lv_obj_set_height(ui_swGenEnable, 29);
    lv_obj_set_x(ui_swGenEnable, 0);
    lv_obj_set_y(ui_swGenEnable, 62);
    lv_obj_set_align(ui_swGenEnable, LV_ALIGN_CENTER);

    lv_obj_set_style_border_color(ui_swGenEnable, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_swGenEnable, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_swGenEnable, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblGenEnable = lv_label_create(ui_Generator);
    lv_obj_set_width(ui_lblGenEnable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGenEnable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblGenEnable, 0);
    lv_obj_set_y(ui_lblGenEnable, 36);
    lv_obj_set_align(ui_lblGenEnable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblGenEnable, "ON/OFF");
    lv_obj_set_style_text_color(ui_lblGenEnable, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblGenEnable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddl1101GenPreset = lv_dropdown_create(ui_Generator);
    lv_dropdown_set_options(ui_ddl1101GenPreset,
                            "< Manual\n300.00\n303.87\n304.25\n310.00\n315.00\n318.00\n390.00\n418.00\n433.07\n433.92\n434.42\n434.77\n438.90\n868.3\n868.35\n868.865\n868.95\n915.00\n925.00");
    lv_obj_set_width(ui_ddl1101GenPreset, 102);
    lv_obj_set_height(ui_ddl1101GenPreset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddl1101GenPreset, 86);
    lv_obj_set_y(ui_ddl1101GenPreset, -131);
    lv_obj_set_align(ui_ddl1101GenPreset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ddl1101GenPreset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_lbl1101GenPreset = lv_label_create(ui_Generator);
    lv_obj_set_width(ui_lbl1101GenPreset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl1101GenPreset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl1101GenPreset, 84);
    lv_obj_set_y(ui_lbl1101GenPreset, -102);
    lv_obj_set_align(ui_lbl1101GenPreset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl1101GenPreset, "PRESET");
    lv_obj_set_style_text_color(ui_lbl1101GenPreset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl1101GenPreset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecPlayback = lv_tabview_add_tab(ui_tabCC1101Stuff, "REC/PLAY");

    ui_indRed = lv_img_create(ui_RecPlayback);
    lv_img_set_src(ui_indRed, &ui_img_txind_png);
    lv_obj_set_width(ui_indRed, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_indRed, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_indRed, 111);
    lv_obj_set_y(ui_indRed, -119);
    lv_obj_set_align(ui_indRed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_indRed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_indRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_indGreen = lv_img_create(ui_RecPlayback);
    lv_img_set_src(ui_indGreen, &ui_img_rxind_png);
    lv_obj_set_width(ui_indGreen, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_indGreen, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_indGreen, 81);
    lv_obj_set_y(ui_indGreen, -119);
    lv_obj_set_align(ui_indGreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_indGreen, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_indGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_indGreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCapture = lv_btn_create(ui_RecPlayback);
    lv_obj_set_width(ui_btnCapture, 83);
    lv_obj_set_height(ui_btnCapture, 42);
    lv_obj_set_x(ui_btnCapture, -107);
    lv_obj_set_y(ui_btnCapture, -45);
    lv_obj_set_align(ui_btnCapture, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCapture, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCapture, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblCapture = lv_label_create(ui_btnCapture);
    lv_obj_set_width(ui_lblCapture, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCapture, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCapture, 0);
    lv_obj_set_y(ui_lblCapture, 1);
    lv_obj_set_align(ui_lblCapture, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCapture, "CAPTURE");

    ui_btnPlayback = lv_btn_create(ui_RecPlayback);
    lv_obj_set_width(ui_btnPlayback, 87);
    lv_obj_set_height(ui_btnPlayback, 42);
    lv_obj_set_x(ui_btnPlayback, 105);
    lv_obj_set_y(ui_btnPlayback, -45);
    lv_obj_set_align(ui_btnPlayback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPlayback, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnPlayback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblPlayback = lv_label_create(ui_btnPlayback);
    lv_obj_set_width(ui_lblPlayback, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPlayback, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPlayback, 0);
    lv_obj_set_y(ui_lblPlayback, 1);
    lv_obj_set_align(ui_lblPlayback, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPlayback, "PLAYBACK");

    ui_lblRecPlayStatus = lv_label_create(ui_RecPlayback);
    lv_obj_set_width(ui_lblRecPlayStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRecPlayStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRecPlayStatus, 0);
    lv_obj_set_y(ui_lblRecPlayStatus, -155);
    lv_obj_set_align(ui_lblRecPlayStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRecPlayStatus, "Status");
    lv_obj_set_style_text_color(ui_lblRecPlayStatus, lv_color_hex(0xDEFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRecPlayStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtRecPlayFq = lv_textarea_create(ui_RecPlayback);
    lv_obj_set_width(ui_txtRecPlayFq, 120);
    lv_obj_set_height(ui_txtRecPlayFq, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_txtRecPlayFq, 0);
    lv_obj_set_y(ui_txtRecPlayFq, -119);
    lv_obj_set_align(ui_txtRecPlayFq, LV_ALIGN_CENTER);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_txtRecPlayFq, NULL);
    else lv_textarea_set_accepted_chars(ui_txtRecPlayFq, "1234567890.");
    lv_textarea_set_max_length(ui_txtRecPlayFq, 6);
    lv_textarea_set_text(ui_txtRecPlayFq, "433.92");
    lv_textarea_set_one_line(ui_txtRecPlayFq, true);
    lv_obj_set_style_text_color(ui_txtRecPlayFq, lv_color_hex(0x00FFEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtRecPlayFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtRecPlayFq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtRecPlayFq, &ui_font_LCD20at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtRecPlayFq, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtRecPlayFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Preset = lv_dropdown_create(ui_RecPlayback);
    lv_dropdown_set_options(ui_Preset, "AM650\nAM270\nFM238\nFM476");
    lv_obj_set_width(ui_Preset, 96);
    lv_obj_set_height(ui_Preset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset, 0);
    lv_obj_set_y(ui_Preset, -49);
    lv_obj_set_align(ui_Preset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Preset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_lblRadioPreset = lv_label_create(ui_RecPlayback);
    lv_obj_set_width(ui_lblRadioPreset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRadioPreset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRadioPreset, 0);
    lv_obj_set_y(ui_lblRadioPreset, -78);
    lv_obj_set_align(ui_lblRadioPreset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRadioPreset, "Radio Preset");
    lv_obj_set_style_text_color(ui_lblRadioPreset, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRadioPreset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSave = lv_btn_create(ui_RecPlayback);
    lv_obj_set_width(ui_btnSave, 67);
    lv_obj_set_height(ui_btnSave, 25);
    lv_obj_set_x(ui_btnSave, 0);
    lv_obj_set_y(ui_btnSave, 113);
    lv_obj_set_align(ui_btnSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSave, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblSave = lv_label_create(ui_btnSave);
    lv_obj_set_width(ui_lblSave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSave, 0);
    lv_obj_set_y(ui_lblSave, 2);
    lv_obj_set_align(ui_lblSave, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSave, "SAVE");

    ui_txtRawData = lv_textarea_create(ui_RecPlayback);
    lv_obj_set_width(ui_txtRawData, 300);
    lv_obj_set_height(ui_txtRawData, 99);
    lv_obj_set_x(ui_txtRawData, 0);
    lv_obj_set_y(ui_txtRawData, 39);
    lv_obj_set_align(ui_txtRawData, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtRawData, "Raw Data...");



    ui_btnCapture1 = lv_btn_create(ui_RecPlayback);
    lv_obj_set_width(ui_btnCapture1, 83);
    lv_obj_set_height(ui_btnCapture1, 42);
    lv_obj_set_x(ui_btnCapture1, 0);
    lv_obj_set_y(ui_btnCapture1, 123);
    lv_obj_set_align(ui_btnCapture1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCapture1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCapture1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblCapture1 = lv_label_create(ui_btnCapture1);
    lv_obj_set_width(ui_lblCapture1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCapture1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCapture1, 0);
    lv_obj_set_y(ui_lblCapture1, 1);
    lv_obj_set_align(ui_lblCapture1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCapture1, "SAVE");

    ui_Config = lv_tabview_add_tab(ui_tabCC1101Stuff, "CONFIG");

    ui_arcScanBW = lv_arc_create(ui_Config);
    lv_obj_set_width(ui_arcScanBW, 77);
    lv_obj_set_height(ui_arcScanBW, 77);
    lv_obj_set_x(ui_arcScanBW, 96);
    lv_obj_set_y(ui_arcScanBW, -24);
    lv_obj_set_align(ui_arcScanBW, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_arcScanBW, 58, 812);
    lv_arc_set_value(ui_arcScanBW, 256);
    lv_obj_set_style_bg_color(ui_arcScanBW, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcScanBW, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arcScanBW, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcScanBW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcScanBW, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arcScanBW, lv_color_hex(0xFF9100), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcScanBW, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcScanBW, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcScanBW, lv_color_hex(0x0096FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcScanBW, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_arcScanBW, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_arcScanBW, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcScanBW, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblRXBWArc = lv_label_create(ui_arcScanBW);
    lv_obj_set_width(ui_lblRXBWArc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRXBWArc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRXBWArc, -1);
    lv_obj_set_y(ui_lblRXBWArc, 0);
    lv_obj_set_align(ui_lblRXBWArc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRXBWArc, "256");
    lv_obj_set_style_text_color(ui_lblRXBWArc, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRXBWArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRXBWArc, &ui_font_Verdana24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRXBWKhz = lv_label_create(ui_arcScanBW);
    lv_obj_set_width(ui_lblRXBWKhz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRXBWKhz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRXBWKhz, 0);
    lv_obj_set_y(ui_lblRXBWKhz, 25);
    lv_obj_set_align(ui_lblRXBWKhz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRXBWKhz, "Khz");
    lv_obj_set_style_text_color(ui_lblRXBWKhz, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRXBWKhz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddlCC1101ModType = lv_dropdown_create(ui_Config);
    lv_dropdown_set_options(ui_ddlCC1101ModType, "ASK/OOK\n2-FSK\n4-FSK\nGFSK\nMSK");
    lv_obj_set_width(ui_ddlCC1101ModType, 150);
    lv_obj_set_height(ui_ddlCC1101ModType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddlCC1101ModType, -76);
    lv_obj_set_y(ui_ddlCC1101ModType, -134);
    lv_obj_set_align(ui_ddlCC1101ModType, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ddlCC1101ModType, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ddlCC1101ModType, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ddlCC1101ModType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ddlCC1101ModType, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ddlCC1101ModType, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ddlCC1101ModType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ddlCC1101ModType, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ddlCC1101ModType, 100, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_lblCC1101ModType = lv_label_create(ui_Config);
    lv_obj_set_width(ui_lblCC1101ModType, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCC1101ModType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCC1101ModType, -110);
    lv_obj_set_y(ui_lblCC1101ModType, -158);
    lv_obj_set_align(ui_lblCC1101ModType, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCC1101ModType, "MODULATION");
    lv_obj_set_style_text_color(ui_lblCC1101ModType, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCC1101ModType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCC1101ModType, &ui_font_Verdana11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddlCC1101PktFormat = lv_dropdown_create(ui_Config);
    lv_dropdown_set_options(ui_ddlCC1101PktFormat, "NORMAL\nSYNCHRONOUS\nRANDOM TX\nASYNCHRONOUS");
    lv_obj_set_width(ui_ddlCC1101PktFormat, 150);
    lv_obj_set_height(ui_ddlCC1101PktFormat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddlCC1101PktFormat, -75);
    lv_obj_set_y(ui_ddlCC1101PktFormat, -73);
    lv_obj_set_align(ui_ddlCC1101PktFormat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ddlCC1101PktFormat, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ddlCC1101PktFormat, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ddlCC1101PktFormat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ddlCC1101PktFormat, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ddlCC1101PktFormat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ddlCC1101PktFormat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ddlCC1101PktFormat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ddlCC1101PktFormat, 100, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_lblCC1101PktFormat = lv_label_create(ui_Config);
    lv_obj_set_width(ui_lblCC1101PktFormat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCC1101PktFormat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCC1101PktFormat, -100);
    lv_obj_set_y(ui_lblCC1101PktFormat, -97);
    lv_obj_set_align(ui_lblCC1101PktFormat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCC1101PktFormat, "PACKET FORMAT");
    lv_obj_set_style_text_color(ui_lblCC1101PktFormat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCC1101PktFormat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCC1101PktFormat, &ui_font_Verdana11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblScannerBW = lv_label_create(ui_Config);
    lv_obj_set_width(ui_lblScannerBW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScannerBW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblScannerBW, 97);
    lv_obj_set_y(ui_lblScannerBW, -73);
    lv_obj_set_align(ui_lblScannerBW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScannerBW, "RX BANDWIDTH");
    lv_obj_set_style_text_color(ui_lblScannerBW, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblScannerBW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblScannerBW, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Config1101Preset = lv_dropdown_create(ui_Config);
    lv_dropdown_set_options(ui_Config1101Preset, "AM650\nAM270\nFM238\nFM476");
    lv_obj_set_width(ui_Config1101Preset, 96);
    lv_obj_set_height(ui_Config1101Preset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Config1101Preset, 98);
    lv_obj_set_y(ui_Config1101Preset, -131);
    lv_obj_set_align(ui_Config1101Preset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Config1101Preset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_lblCC1101ModType2 = lv_label_create(ui_Config);
    lv_obj_set_width(ui_lblCC1101ModType2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCC1101ModType2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCC1101ModType2, 97);
    lv_obj_set_y(ui_lblCC1101ModType2, -158);
    lv_obj_set_align(ui_lblCC1101ModType2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCC1101ModType2, "PRESET");
    lv_obj_set_style_text_color(ui_lblCC1101ModType2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCC1101ModType2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCC1101ModType2, &ui_font_Verdana11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcDeviation = lv_arc_create(ui_Config);
    lv_obj_set_width(ui_arcDeviation, 77);
    lv_obj_set_height(ui_arcDeviation, 77);
    lv_obj_set_x(ui_arcDeviation, 95);
    lv_obj_set_y(ui_arcDeviation, 80);
    lv_obj_set_align(ui_arcDeviation, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_arcDeviation, 2, 380);
    lv_arc_set_value(ui_arcDeviation, 5);
    lv_obj_set_style_bg_color(ui_arcDeviation, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcDeviation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arcDeviation, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcDeviation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcDeviation, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arcDeviation, lv_color_hex(0xFF9100), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcDeviation, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcDeviation, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcDeviation, lv_color_hex(0x0096FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcDeviation, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_arcDeviation, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_arcDeviation, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcDeviation, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblDeviation = lv_label_create(ui_arcDeviation);
    lv_obj_set_width(ui_lblDeviation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDeviation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDeviation, -1);
    lv_obj_set_y(ui_lblDeviation, 0);
    lv_obj_set_align(ui_lblDeviation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDeviation, "5");
    lv_obj_set_style_text_color(ui_lblDeviation, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDeviation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDeviation, &ui_font_Verdana24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDeviationKhz = lv_label_create(ui_arcDeviation);
    lv_obj_set_width(ui_lblDeviationKhz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDeviationKhz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDeviationKhz, 0);
    lv_obj_set_y(ui_lblDeviationKhz, 25);
    lv_obj_set_align(ui_lblDeviationKhz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDeviationKhz, "Khz");
    lv_obj_set_style_text_color(ui_lblDeviationKhz, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDeviationKhz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblScannerBW1 = lv_label_create(ui_Config);
    lv_obj_set_width(ui_lblScannerBW1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScannerBW1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblScannerBW1, 98);
    lv_obj_set_y(ui_lblScannerBW1, 32);
    lv_obj_set_align(ui_lblScannerBW1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScannerBW1, "DEVIATION");
    lv_obj_set_style_text_color(ui_lblScannerBW1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblScannerBW1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblScannerBW1, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnScanBack = lv_btn_create(ui_scrCC1101Stuff);
    lv_obj_set_width(ui_btnScanBack, 90);
    lv_obj_set_height(ui_btnScanBack, 30);
    lv_obj_set_x(ui_btnScanBack, -115);
    lv_obj_set_y(ui_btnScanBack, 224);
    lv_obj_set_align(ui_btnScanBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnScanBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnScanBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnScanBack, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnScanBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblScanBack = lv_label_create(ui_btnScanBack);
    lv_obj_set_width(ui_lblScanBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScanBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblScanBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScanBack, "BACK");
    lv_obj_set_style_text_color(ui_lblScanBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblScanBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblScanBack, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelCC1101StuffFreqKeyboard = lv_obj_create(ui_scrCC1101Stuff);
    lv_obj_set_width(ui_panelCC1101StuffFreqKeyboard, 320);
    lv_obj_set_height(ui_panelCC1101StuffFreqKeyboard, 480);
    lv_obj_set_align(ui_panelCC1101StuffFreqKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_panelCC1101StuffFreqKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_panelCC1101StuffFreqKeyboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelCC1101StuffFreqKeyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelCC1101StuffFreqKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_panelCC1101StuffFreqKeyboard, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelCC1101StuffFreqKeyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelCC1101StuffFreqKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCC1101StuffFreqKeyboardValueUnits = lv_label_create(ui_panelCC1101StuffFreqKeyboard);
    lv_obj_set_width(ui_lblCC1101StuffFreqKeyboardValueUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCC1101StuffFreqKeyboardValueUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCC1101StuffFreqKeyboardValueUnits, 0);
    lv_obj_set_y(ui_lblCC1101StuffFreqKeyboardValueUnits, -165);
    lv_obj_set_align(ui_lblCC1101StuffFreqKeyboardValueUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCC1101StuffFreqKeyboardValueUnits, "mHz");
    lv_obj_set_style_text_color(ui_lblCC1101StuffFreqKeyboardValueUnits, lv_color_hex(0x00FFEB),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCC1101StuffFreqKeyboardValueUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCC1101StuffFreqKeyboardValueUnits, &ui_font_LCD20at8BPP,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCC1101StuffFreqKeyboardTitle = lv_label_create(ui_panelCC1101StuffFreqKeyboard);
    lv_obj_set_width(ui_lblCC1101StuffFreqKeyboardTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCC1101StuffFreqKeyboardTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCC1101StuffFreqKeyboardTitle, 0);
    lv_obj_set_y(ui_lblCC1101StuffFreqKeyboardTitle, -223);
    lv_obj_set_align(ui_lblCC1101StuffFreqKeyboardTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCC1101StuffFreqKeyboardTitle, "Enter Value");
    lv_obj_set_style_text_color(ui_lblCC1101StuffFreqKeyboardTitle, lv_color_hex(0xFF9100),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCC1101StuffFreqKeyboardTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCC1101StuffFreqKeyboardTitle, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_txtScanStopFq, ui_event_txtScanStopFq, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtScanStartFq, ui_event_txtScanStartFq, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swScannerOn, ui_event_swScannerOn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnScannerClear, ui_event_btnScannerClear, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sldThreshold, ui_event_sldThreshold, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ddl1101ScanPreset, ui_event_ddl1101ScanPreset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txt1101GenFreq, ui_event_txt1101GenFreq, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swGenEnable, ui_event_swGenEnable, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ddl1101GenPreset, ui_event_ddl1101GenPreset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnCapture, ui_event_btnCapture, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lblPlayback, ui_event_lblPlayback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnPlayback, ui_event_btnPlayback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtRecPlayFq, ui_event_txtRecPlayFq, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Preset, ui_event_Preset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnCapture1, ui_event_btnCapture1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arcScanBW, ui_event_arcScanBW, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ddlCC1101ModType, ui_event_ddlCC1101ModType, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ddlCC1101PktFormat, ui_event_ddlCC1101PktFormat, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Config1101Preset, ui_event_Config1101Preset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arcDeviation, ui_event_arcDeviation, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tabCC1101Stuff, ui_event_tabCC1101Stuff, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnScanBack, ui_event_btnScanBack, LV_EVENT_ALL, NULL);

}
