// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: WaveSentinel

#include "../ui.h"

void ui_scrSplash_screen_init(void)
{
    ui_scrSplash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrSplash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrSplash, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrSplash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_scrSplash, &ui_img_wavesentinelnew_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSplash = lv_label_create(ui_scrSplash);
    lv_obj_set_width(ui_lblSplash, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSplash, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSplash, 87);
    lv_obj_set_y(ui_lblSplash, 227);
    lv_obj_set_align(ui_lblSplash, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSplash, "STATUS");
    lv_obj_set_style_text_color(ui_lblSplash, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSplash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSplash, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSplash, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSplashStatus = lv_label_create(ui_scrSplash);
    lv_obj_set_width(ui_lblSplashStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSplashStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSplashStatus, 1);
    lv_obj_set_y(ui_lblSplashStatus, -229);
    lv_obj_set_align(ui_lblSplashStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSplashStatus, "");
    lv_obj_set_style_text_color(ui_lblSplashStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSplashStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSplashStatus, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSplashStatus, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblVersion = lv_label_create(ui_scrSplash);
    lv_obj_set_width(ui_lblVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblVersion, -93);
    lv_obj_set_y(ui_lblVersion, 227);
    lv_obj_set_align(ui_lblVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVersion, "");
    lv_obj_set_style_text_color(ui_lblVersion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblVersion, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblVersion, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_scrSplash, ui_event_scrSplash, LV_EVENT_ALL, NULL);

}
