// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: WaveSentinel

#include "../ui.h"

void ui_scrProtAna_screen_init(void)
{
    ui_scrProtAna = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrProtAna, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrProtAna, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrProtAna, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_scrProtAna, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblProtAnalyzerTitle = lv_label_create(ui_scrProtAna);
    lv_obj_set_width(ui_lblProtAnalyzerTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnalyzerTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProtAnalyzerTitle, 7);
    lv_obj_set_y(ui_lblProtAnalyzerTitle, -223);
    lv_obj_set_align(ui_lblProtAnalyzerTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnalyzerTitle, "PROTOCOL ANALYZER");
    lv_obj_set_style_text_color(ui_lblProtAnalyzerTitle, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnalyzerTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnalyzerTitle, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtProtAnaResults = lv_textarea_create(ui_scrProtAna);
    lv_obj_set_width(ui_txtProtAnaResults, 306);
    lv_obj_set_height(ui_txtProtAnaResults, 131);
    lv_obj_set_x(ui_txtProtAnaResults, -1);
    lv_obj_set_y(ui_txtProtAnaResults, 75);
    lv_obj_set_align(ui_txtProtAnaResults, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_txtProtAnaResults, 0);
    lv_textarea_set_placeholder_text(ui_txtProtAnaResults, "Raw Signal Info...");
    lv_obj_clear_flag(ui_txtProtAnaResults, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_txtProtAnaResults, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtProtAnaResults, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtProtAnaResults, &ui_font_Verdana16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_txtProtAnaResults, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_btnProtAnaCncl = lv_btn_create(ui_scrProtAna);
    lv_obj_set_width(ui_btnProtAnaCncl, 90);
    lv_obj_set_height(ui_btnProtAnaCncl, 30);
    lv_obj_set_x(ui_btnProtAnaCncl, -114);
    lv_obj_set_y(ui_btnProtAnaCncl, 224);
    lv_obj_set_align(ui_btnProtAnaCncl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnProtAnaCncl, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnProtAnaCncl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnProtAnaCncl, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnProtAnaCncl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblProtAnaCncl = lv_label_create(ui_btnProtAnaCncl);
    lv_obj_set_width(ui_lblProtAnaCncl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnaCncl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblProtAnaCncl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnaCncl, "BACK");
    lv_obj_set_style_text_color(ui_lblProtAnaCncl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnaCncl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnaCncl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnProtAnaClear = lv_btn_create(ui_scrProtAna);
    lv_obj_set_width(ui_btnProtAnaClear, 83);
    lv_obj_set_height(ui_btnProtAnaClear, 30);
    lv_obj_set_x(ui_btnProtAnaClear, -10);
    lv_obj_set_y(ui_btnProtAnaClear, 162);
    lv_obj_set_align(ui_btnProtAnaClear, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnProtAnaClear, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnProtAnaClear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnProtAnaClear, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnProtAnaClear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblProtAnaClear = lv_label_create(ui_btnProtAnaClear);
    lv_obj_set_width(ui_lblProtAnaClear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnaClear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblProtAnaClear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnaClear, "CLEAR");
    lv_obj_set_style_text_color(ui_lblProtAnaClear, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnaClear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnaClear, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swtProtAnaRxEn = lv_switch_create(ui_scrProtAna);
    lv_obj_set_width(ui_swtProtAnaRxEn, 61);
    lv_obj_set_height(ui_swtProtAnaRxEn, 26);
    lv_obj_set_x(ui_swtProtAnaRxEn, 74);
    lv_obj_set_y(ui_swtProtAnaRxEn, 161);
    lv_obj_set_align(ui_swtProtAnaRxEn, LV_ALIGN_CENTER);


    ui_lblProtAnaRXEn = lv_label_create(ui_scrProtAna);
    lv_obj_set_width(ui_lblProtAnaRXEn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnaRXEn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProtAnaRXEn, 132);
    lv_obj_set_y(ui_lblProtAnaRXEn, 160);
    lv_obj_set_align(ui_lblProtAnaRXEn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnaRXEn, "ON/OFF");
    lv_obj_set_style_text_color(ui_lblProtAnaRXEn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnaRXEn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnaRXEn, &ui_font_Verdana11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMainFreq = lv_label_create(ui_scrProtAna);
    lv_obj_set_width(ui_lblMainFreq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMainFreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMainFreq, -59);
    lv_obj_set_y(ui_lblMainFreq, -200);
    lv_obj_set_align(ui_lblMainFreq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMainFreq, "FREQUENCY (MHz)");
    lv_obj_set_style_text_color(ui_lblMainFreq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMainFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMainFreq, &ui_font_Verdana14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtMainFreq = lv_textarea_create(ui_scrProtAna);
    lv_obj_set_width(ui_txtMainFreq, 173);
    lv_obj_set_height(ui_txtMainFreq, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_txtMainFreq, -58);
    lv_obj_set_y(ui_txtMainFreq, -171);
    lv_obj_set_align(ui_txtMainFreq, LV_ALIGN_CENTER);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_txtMainFreq, NULL);
    else lv_textarea_set_accepted_chars(ui_txtMainFreq, "1234567890.");
    lv_textarea_set_max_length(ui_txtMainFreq, 6);
    lv_textarea_set_text(ui_txtMainFreq, "433.92");
    lv_textarea_set_one_line(ui_txtMainFreq, true);
    lv_obj_set_style_text_color(ui_txtMainFreq, lv_color_hex(0x00FFEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtMainFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtMainFreq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtMainFreq, &ui_font_LCD20at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtMainFreq, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtMainFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_lblProtAnaReceived = lv_label_create(ui_scrProtAna);
    lv_obj_set_width(ui_lblProtAnaReceived, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnaReceived, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProtAnaReceived, -90);
    lv_obj_set_y(ui_lblProtAnaReceived, -141);
    lv_obj_set_align(ui_lblProtAnaReceived, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnaReceived, "RECEIVED");
    lv_obj_set_style_text_color(ui_lblProtAnaReceived, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnaReceived, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblProtAnaReceived, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnaReceived, &ui_font_Verdana11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblProtAnaBitLength = lv_label_create(ui_scrProtAna);
    lv_obj_set_width(ui_lblProtAnaBitLength, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnaBitLength, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProtAnaBitLength, -8);
    lv_obj_set_y(ui_lblProtAnaBitLength, -141);
    lv_obj_set_align(ui_lblProtAnaBitLength, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnaBitLength, "BIT LEN");
    lv_obj_set_style_text_color(ui_lblProtAnaBitLength, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnaBitLength, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblProtAnaBitLength, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnaBitLength, &ui_font_Verdana11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtProtAnaReceived = lv_textarea_create(ui_scrProtAna);
    lv_obj_set_width(ui_txtProtAnaReceived, 107);
    lv_obj_set_height(ui_txtProtAnaReceived, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtProtAnaReceived, -91);
    lv_obj_set_y(ui_txtProtAnaReceived, -117);
    lv_obj_set_align(ui_txtProtAnaReceived, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_txtProtAnaReceived, "-");
    lv_obj_clear_flag(ui_txtProtAnaReceived, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_txtProtAnaReceived, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_txtProtAnaReceived, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtProtAnaReceived, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtProtAnaReceived, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_txtProtAnaReceived, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtProtAnaReceived, &ui_font_Verdana16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtProtAnaReceived, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtProtAnaReceived, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_txtProtAnaBitLength = lv_textarea_create(ui_scrProtAna);
    lv_obj_set_width(ui_txtProtAnaBitLength, 52);
    lv_obj_set_height(ui_txtProtAnaBitLength, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtProtAnaBitLength, -7);
    lv_obj_set_y(ui_txtProtAnaBitLength, -117);
    lv_obj_set_align(ui_txtProtAnaBitLength, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_txtProtAnaBitLength, "-");
    lv_obj_clear_flag(ui_txtProtAnaBitLength,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_scrollbar_mode(ui_txtProtAnaBitLength, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_txtProtAnaBitLength, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtProtAnaBitLength, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtProtAnaBitLength, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_txtProtAnaBitLength, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtProtAnaBitLength, &ui_font_Verdana16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtProtAnaBitLength, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtProtAnaBitLength, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_lblProtAnaBinary = lv_label_create(ui_scrProtAna);
    lv_obj_set_width(ui_lblProtAnaBinary, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnaBinary, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProtAnaBinary, 0);
    lv_obj_set_y(ui_lblProtAnaBinary, -88);
    lv_obj_set_align(ui_lblProtAnaBinary, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnaBinary, "BINARY");
    lv_obj_set_style_text_color(ui_lblProtAnaBinary, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnaBinary, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblProtAnaBinary, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnaBinary, &ui_font_Verdana11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtProtAnaBinary = lv_textarea_create(ui_scrProtAna);
    lv_obj_set_width(ui_txtProtAnaBinary, 286);
    lv_obj_set_height(ui_txtProtAnaBinary, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtProtAnaBinary, 0);
    lv_obj_set_y(ui_txtProtAnaBinary, -65);
    lv_obj_set_align(ui_txtProtAnaBinary, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_txtProtAnaBinary, "-");
    lv_obj_clear_flag(ui_txtProtAnaBinary, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_txtProtAnaBinary, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_txtProtAnaBinary, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtProtAnaBinary, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtProtAnaBinary, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_txtProtAnaBinary, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtProtAnaBinary, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtProtAnaBinary, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtProtAnaBinary, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_lblProtAnaPulsLen = lv_label_create(ui_scrProtAna);
    lv_obj_set_width(ui_lblProtAnaPulsLen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnaPulsLen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProtAnaPulsLen, 60);
    lv_obj_set_y(ui_lblProtAnaPulsLen, -141);
    lv_obj_set_align(ui_lblProtAnaPulsLen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnaPulsLen, "PULSE LEN");
    lv_obj_set_style_text_color(ui_lblProtAnaPulsLen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnaPulsLen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblProtAnaPulsLen, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnaPulsLen, &ui_font_Verdana11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtProtAnaPulsLen = lv_textarea_create(ui_scrProtAna);
    lv_obj_set_width(ui_txtProtAnaPulsLen, 75);
    lv_obj_set_height(ui_txtProtAnaPulsLen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtProtAnaPulsLen, 60);
    lv_obj_set_y(ui_txtProtAnaPulsLen, -117);
    lv_obj_set_align(ui_txtProtAnaPulsLen, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_txtProtAnaPulsLen, "-");
    lv_obj_clear_flag(ui_txtProtAnaPulsLen,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_scrollbar_mode(ui_txtProtAnaPulsLen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_txtProtAnaPulsLen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtProtAnaPulsLen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtProtAnaPulsLen, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_txtProtAnaPulsLen, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtProtAnaPulsLen, &ui_font_Verdana16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtProtAnaPulsLen, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtProtAnaPulsLen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_lblProtAnaTriState = lv_label_create(ui_scrProtAna);
    lv_obj_set_width(ui_lblProtAnaTriState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnaTriState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProtAnaTriState, 0);
    lv_obj_set_y(ui_lblProtAnaTriState, -37);
    lv_obj_set_align(ui_lblProtAnaTriState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnaTriState, "TRISTATE");
    lv_obj_set_style_text_color(ui_lblProtAnaTriState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnaTriState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblProtAnaTriState, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnaTriState, &ui_font_Verdana11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtProtAnaProtAnaTriState = lv_textarea_create(ui_scrProtAna);
    lv_obj_set_width(ui_txtProtAnaProtAnaTriState, 286);
    lv_obj_set_height(ui_txtProtAnaProtAnaTriState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtProtAnaProtAnaTriState, 0);
    lv_obj_set_y(ui_txtProtAnaProtAnaTriState, -14);
    lv_obj_set_align(ui_txtProtAnaProtAnaTriState, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_txtProtAnaProtAnaTriState, "-");
    lv_obj_clear_flag(ui_txtProtAnaProtAnaTriState,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_txtProtAnaProtAnaTriState, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_txtProtAnaProtAnaTriState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtProtAnaProtAnaTriState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtProtAnaProtAnaTriState, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_txtProtAnaProtAnaTriState, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtProtAnaProtAnaTriState, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtProtAnaProtAnaTriState, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtProtAnaProtAnaTriState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_txtProtAnaProtocol = lv_textarea_create(ui_scrProtAna);
    lv_obj_set_width(ui_txtProtAnaProtocol, 42);
    lv_obj_set_height(ui_txtProtAnaProtocol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtProtAnaProtocol, 123);
    lv_obj_set_y(ui_txtProtAnaProtocol, -117);
    lv_obj_set_align(ui_txtProtAnaProtocol, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_txtProtAnaProtocol, "-");
    lv_obj_clear_flag(ui_txtProtAnaProtocol,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_scrollbar_mode(ui_txtProtAnaProtocol, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_txtProtAnaProtocol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtProtAnaProtocol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtProtAnaProtocol, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_txtProtAnaProtocol, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtProtAnaProtocol, &ui_font_Verdana16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtProtAnaProtocol, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtProtAnaProtocol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_lblProtAnaProtocol = lv_label_create(ui_scrProtAna);
    lv_obj_set_width(ui_lblProtAnaProtocol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnaProtocol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProtAnaProtocol, 123);
    lv_obj_set_y(ui_lblProtAnaProtocol, -141);
    lv_obj_set_align(ui_lblProtAnaProtocol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnaProtocol, "PROTO");
    lv_obj_set_style_text_color(ui_lblProtAnaProtocol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnaProtocol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblProtAnaProtocol, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnaProtocol, &ui_font_Verdana11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnProtanaReplay = lv_btn_create(ui_scrProtAna);
    lv_obj_set_width(ui_btnProtanaReplay, 90);
    lv_obj_set_height(ui_btnProtanaReplay, 30);
    lv_obj_set_x(ui_btnProtanaReplay, -105);
    lv_obj_set_y(ui_btnProtanaReplay, 162);
    lv_obj_set_align(ui_btnProtanaReplay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnProtanaReplay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnProtanaReplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblProtanaReplay = lv_label_create(ui_btnProtanaReplay);
    lv_obj_set_width(ui_lblProtanaReplay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtanaReplay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProtanaReplay, -1);
    lv_obj_set_y(ui_lblProtanaReplay, 1);
    lv_obj_set_align(ui_lblProtanaReplay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtanaReplay, "REPLAY");
    lv_obj_set_style_text_font(ui_lblProtanaReplay, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblProtAnaPreset = lv_label_create(ui_scrProtAna);
    lv_obj_set_width(ui_lblProtAnaPreset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnaPreset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProtAnaPreset, 101);
    lv_obj_set_y(ui_lblProtAnaPreset, -201);
    lv_obj_set_align(ui_lblProtAnaPreset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnaPreset, "RADIO PRESET");
    lv_obj_set_style_text_color(ui_lblProtAnaPreset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnaPreset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblProtAnaPreset, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnaPreset, &ui_font_Verdana11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProtanaPreset = lv_dropdown_create(ui_scrProtAna);
    lv_dropdown_set_options(ui_ProtanaPreset, "AM650\nAM270\nFM238\nFM476");
    lv_obj_set_width(ui_ProtanaPreset, 96);
    lv_obj_set_height(ui_ProtanaPreset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProtanaPreset, 103);
    lv_obj_set_y(ui_ProtanaPreset, -173);
    lv_obj_set_align(ui_ProtanaPreset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProtanaPreset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_panelProtAnaFreqKeyboard = lv_obj_create(ui_scrProtAna);
    lv_obj_set_width(ui_panelProtAnaFreqKeyboard, 320);
    lv_obj_set_height(ui_panelProtAnaFreqKeyboard, 480);
    lv_obj_set_align(ui_panelProtAnaFreqKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_panelProtAnaFreqKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_panelProtAnaFreqKeyboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelProtAnaFreqKeyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelProtAnaFreqKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_panelProtAnaFreqKeyboard, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelProtAnaFreqKeyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelProtAnaFreqKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblProtAnaFreqKeyboardValueUnits = lv_label_create(ui_panelProtAnaFreqKeyboard);
    lv_obj_set_width(ui_lblProtAnaFreqKeyboardValueUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnaFreqKeyboardValueUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProtAnaFreqKeyboardValueUnits, 0);
    lv_obj_set_y(ui_lblProtAnaFreqKeyboardValueUnits, -165);
    lv_obj_set_align(ui_lblProtAnaFreqKeyboardValueUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnaFreqKeyboardValueUnits, "mHz");
    lv_obj_set_style_text_color(ui_lblProtAnaFreqKeyboardValueUnits, lv_color_hex(0x00FFEB),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnaFreqKeyboardValueUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnaFreqKeyboardValueUnits, &ui_font_LCD20at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblProtAnaFreqKeyboardTitle = lv_label_create(ui_panelProtAnaFreqKeyboard);
    lv_obj_set_width(ui_lblProtAnaFreqKeyboardTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProtAnaFreqKeyboardTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblProtAnaFreqKeyboardTitle, 0);
    lv_obj_set_y(ui_lblProtAnaFreqKeyboardTitle, -223);
    lv_obj_set_align(ui_lblProtAnaFreqKeyboardTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProtAnaFreqKeyboardTitle, "Enter Value");
    lv_obj_set_style_text_color(ui_lblProtAnaFreqKeyboardTitle, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProtAnaFreqKeyboardTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProtAnaFreqKeyboardTitle, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnProtAnaCncl, ui_event_btnProtAnaCncl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnProtAnaClear, ui_event_btnProtAnaClear, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swtProtAnaRxEn, ui_event_swtProtAnaRxEn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtMainFreq, ui_event_txtMainFreq, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnProtanaReplay, ui_event_btnProtanaReplay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProtanaPreset, ui_event_ProtanaPreset, LV_EVENT_ALL, NULL);

}
