// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: WaveSentinel

#include "../ui.h"

void ui_scrBLEApps_screen_init(void)
{
    ui_scrBLEApps = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrBLEApps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrBLEApps, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiMain1 = lv_label_create(ui_scrBLEApps);
    lv_obj_set_width(ui_lblWifiMain1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiMain1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWifiMain1, 0);
    lv_obj_set_y(ui_lblWifiMain1, -223);
    lv_obj_set_align(ui_lblWifiMain1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWifiMain1, "BLUETOOTH APPLICATIONS");
    lv_obj_set_style_text_color(ui_lblWifiMain1, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWifiMain1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWifiMain1, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tabWifiApps1 = lv_tabview_create(ui_scrBLEApps, LV_DIR_BOTTOM, 30);
    lv_obj_set_width(ui_tabWifiApps1, 320);
    lv_obj_set_height(ui_tabWifiApps1, 364);
    lv_obj_set_x(ui_tabWifiApps1, 0);
    lv_obj_set_y(ui_tabWifiApps1, -18);
    lv_obj_set_align(ui_tabWifiApps1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tabWifiApps1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tabWifiApps1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tabWifiApps1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_tabWifiApps1), lv_color_hex(0xFF9600),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_tabWifiApps1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_tabWifiApps1), &ui_font_Verdana11,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_tabWifiApps1), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_tabWifiApps1), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLESpam = lv_tabview_add_tab(ui_tabWifiApps1, "BLESpam");

    ui_ddlWifiSSID1 = lv_dropdown_create(ui_BLESpam);
    lv_dropdown_set_options(ui_ddlWifiSSID1, "Apple Device Spam\n");
    lv_obj_set_width(ui_ddlWifiSSID1, 289);
    lv_obj_set_height(ui_ddlWifiSSID1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddlWifiSSID1, -1);
    lv_obj_set_y(ui_ddlWifiSSID1, -132);
    lv_obj_set_align(ui_ddlWifiSSID1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ddlWifiSSID1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ddlWifiSSID1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ddlWifiSSID1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ddlWifiSSID1, &ui_font_Verdana14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ddlWifiSSID1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ddlWifiSSID1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_ddlWifiSSID1, &lv_font_montserrat_12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ddlWifiSSID1), &ui_font_Verdana14,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ddlWifiSSID1), &ui_font_Verdana14,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_btnWifiBack1 = lv_btn_create(ui_scrBLEApps);
    lv_obj_set_width(ui_btnWifiBack1, 90);
    lv_obj_set_height(ui_btnWifiBack1, 30);
    lv_obj_set_x(ui_btnWifiBack1, -114);
    lv_obj_set_y(ui_btnWifiBack1, 224);
    lv_obj_set_align(ui_btnWifiBack1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWifiBack1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWifiBack1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnWifiBack1, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWifiBack1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiBack1 = lv_label_create(ui_btnWifiBack1);
    lv_obj_set_width(ui_lblWifiBack1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiBack1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblWifiBack1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWifiBack1, "BACK");
    lv_obj_set_style_text_color(ui_lblWifiBack1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWifiBack1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWifiBack1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swBLEEnable = lv_switch_create(ui_scrBLEApps);
    lv_obj_set_width(ui_swBLEEnable, 101);
    lv_obj_set_height(ui_swBLEEnable, 43);
    lv_obj_set_x(ui_swBLEEnable, 0);
    lv_obj_set_y(ui_swBLEEnable, -66);
    lv_obj_set_align(ui_swBLEEnable, LV_ALIGN_CENTER);


    ui_lblBLEEnable = lv_label_create(ui_scrBLEApps);
    lv_obj_set_width(ui_lblBLEEnable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBLEEnable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBLEEnable, 0);
    lv_obj_set_y(ui_lblBLEEnable, -29);
    lv_obj_set_align(ui_lblBLEEnable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBLEEnable, "OFF - ON");
    lv_obj_set_style_text_color(ui_lblBLEEnable, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBLEEnable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBLEEnable, &ui_font_Verdana16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ddlWifiSSID1, ui_event_ddlWifiSSID1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifiBack1, ui_event_btnWifiBack1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swBLEEnable, ui_event_swBLEEnable, LV_EVENT_ALL, NULL);

}
