// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: WaveSentinel

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_scrSplash
void ui_scrSplash_screen_init(void);
void ui_event_scrSplash(lv_event_t * e);
lv_obj_t * ui_scrSplash;
lv_obj_t * ui_lblSplash;
lv_obj_t * ui_lblSplashStatus;
lv_obj_t * ui_lblVersion;


// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);
lv_obj_t * ui_scrMain;
void ui_event_btnMain1101(lv_event_t * e);
lv_obj_t * ui_btnMain1101;
lv_obj_t * ui_lblMain1101;
void ui_event_btnMainRCSW(lv_event_t * e);
lv_obj_t * ui_btnMainRCSW;
lv_obj_t * ui_lblMainRCSW;
void ui_event_btnMainFlipper(lv_event_t * e);
lv_obj_t * ui_btnMainFlipper;
lv_obj_t * ui_imgMainFlipper;
lv_obj_t * ui_btnMainRecPlay;
void ui_event_btnMainPlayMp3(lv_event_t * e);
lv_obj_t * ui_btnMainPlayMp3;
lv_obj_t * ui_lblMainPlayMp3;
void ui_event_btnMainStopMp3(lv_event_t * e);
lv_obj_t * ui_btnMainStopMp3;
lv_obj_t * ui_lblMainStopMp3;
lv_obj_t * ui_lblMainVolumeMp3;
void ui_event_sliderMainVolumeMp3(lv_event_t * e);
lv_obj_t * ui_sliderMainVolumeMp3;
lv_obj_t * ui_btnMainUnmapped7;
void ui_event_btnMainSettings(lv_event_t * e);
lv_obj_t * ui_btnMainSettings;
void ui_event_btnMainWifi(lv_event_t * e);
lv_obj_t * ui_btnMainWifi;
lv_obj_t * ui_imgMainWifi;
void ui_event_btnMainProtAna(lv_event_t * e);
lv_obj_t * ui_btnMainProtAna;
lv_obj_t * ui_imgMainProtana;
lv_obj_t * ui_lblMainProtAna;
lv_obj_t * ui_lblMainStatus;
lv_obj_t * ui_lblMainSettings;
lv_obj_t * ui_lblMainMenuTitle;


// SCREEN: ui_scrProtAna
void ui_scrProtAna_screen_init(void);
lv_obj_t * ui_scrProtAna;
lv_obj_t * ui_lblProtAnalyzerTitle;
lv_obj_t * ui_txtProtAnaResults;
void ui_event_btnProtAnaCncl(lv_event_t * e);
lv_obj_t * ui_btnProtAnaCncl;
lv_obj_t * ui_lblProtAnaCncl;
void ui_event_btnProtAnaClear(lv_event_t * e);
lv_obj_t * ui_btnProtAnaClear;
lv_obj_t * ui_lblProtAnaClear;
void ui_event_swtProtAnaRxEn(lv_event_t * e);
lv_obj_t * ui_swtProtAnaRxEn;
lv_obj_t * ui_lblProtAnaRXEn;
lv_obj_t * ui_lblMainFreq;
void ui_event_txtMainFreq(lv_event_t * e);
lv_obj_t * ui_txtMainFreq;
lv_obj_t * ui_lblProtAnaReceived;
lv_obj_t * ui_lblProtAnaBitLength;
lv_obj_t * ui_txtProtAnaReceived;
lv_obj_t * ui_txtProtAnaBitLength;
lv_obj_t * ui_lblProtAnaBinary;
lv_obj_t * ui_txtProtAnaBinary;
lv_obj_t * ui_lblProtAnaPulsLen;
lv_obj_t * ui_txtProtAnaPulsLen;
lv_obj_t * ui_lblProtAnaTriState;
lv_obj_t * ui_txtProtAnaProtAnaTriState;
lv_obj_t * ui_txtProtAnaProtocol;
lv_obj_t * ui_lblProtAnaProtocol;
void ui_event_btnProtanaReplay(lv_event_t * e);
lv_obj_t * ui_btnProtanaReplay;
lv_obj_t * ui_lblProtanaReplay;
lv_obj_t * ui_lblProtAnaPreset;
void ui_event_ProtanaPreset(lv_event_t * e);
lv_obj_t * ui_ProtanaPreset;
lv_obj_t * ui_panelProtAnaFreqKeyboard;
lv_obj_t * ui_lblProtAnaFreqKeyboardValueUnits;
lv_obj_t * ui_lblProtAnaFreqKeyboardTitle;


// SCREEN: ui_scrPresets
void ui_scrPresets_screen_init(void);
lv_obj_t * ui_scrPresets;
lv_obj_t * ui_lblPresetsTitle;
lv_obj_t * ui_lblPresetsFolder;
lv_obj_t * ui_lblPresetsFile;
void ui_event_btnPresetsBack(lv_event_t * e);
lv_obj_t * ui_btnPresetsBack;
lv_obj_t * ui_lblPresetsBack;
lv_obj_t * ui_lblPresetsStatus;
void ui_event_ddPresetsFolder(lv_event_t * e);
lv_obj_t * ui_ddPresetsFolder;
void ui_event_ddPresetsFile(lv_event_t * e);
lv_obj_t * ui_ddPresetsFile;
void ui_event_btnPresetTx(lv_event_t * e);
lv_obj_t * ui_btnPresetTx;
lv_obj_t * ui_lblPresetTx;
void ui_event_btnPresetTesla(lv_event_t * e);
lv_obj_t * ui_btnPresetTesla;
lv_obj_t * ui_lblPresetTesla;


// SCREEN: ui_scrSettings
void ui_scrSettings_screen_init(void);
lv_obj_t * ui_scrSettings;
lv_obj_t * ui_lblSettingsTitle;
void ui_event_btnSettingsOTA(lv_event_t * e);
lv_obj_t * ui_btnSettingsOTA;
lv_obj_t * ui_lblSettingsOTA;
lv_obj_t * ui_lblSettingsStatus;
void ui_event_btnSettingsBack(lv_event_t * e);
lv_obj_t * ui_btnSettingsBack;
lv_obj_t * ui_lblSettingsBack;
lv_obj_t * ui_lblSettingsWifiIP;
lv_obj_t * ui_lblSettingsIPAddr;
lv_obj_t * ui_lblSettingsInfo;
lv_obj_t * ui_barProgress;
lv_obj_t * ui_swSettingsWifiMode;
lv_obj_t * ui_lblSettingsWifiSSID;
lv_obj_t * ui_txtSettingsWifiSSID;
lv_obj_t * ui_lblSettingsWifiKey;
lv_obj_t * ui_txtSettingsWifiKey;
lv_obj_t * ui_lblSettingsWifiMode;
lv_obj_t * ui_lblSettingsWifiModeAP;
lv_obj_t * ui_lblSettingsWifiModeSTA;
void ui_event_btnSettingsSave(lv_event_t * e);
lv_obj_t * ui_btnSettingsSave;
lv_obj_t * ui_lblSettingsSave;
void ui_event_btnRotate(lv_event_t * e);
lv_obj_t * ui_btnRotate;
lv_obj_t * ui_lblRotate;
void ui_event_sldBrightness(lv_event_t * e);
lv_obj_t * ui_sldBrightness;
lv_obj_t * ui_Label2;
void ui_event_btnAbout(lv_event_t * e);
lv_obj_t * ui_btnAbout;
lv_obj_t * ui_lblAbout;
void ui_event_btnRestart(lv_event_t * e);
lv_obj_t * ui_btnRestart;
lv_obj_t * ui_lblRestart;
lv_obj_t * ui_panelWiFiKeyboard;
lv_obj_t * ui_txtKybdEntry;
void ui_event_kybdEntry(lv_event_t * e);
lv_obj_t * ui_kybdEntry;
lv_obj_t * ui_lblKybdInstruction;
lv_obj_t * ui_Label1;


// SCREEN: ui_scrWifiApps
void ui_scrWifiApps_screen_init(void);
lv_obj_t * ui_scrWifiApps;
lv_obj_t * ui_lblWifiMain;
lv_obj_t * ui_tabWifiApps;
lv_obj_t * ui_WifiScan;
void ui_event_btnWifiScannerScan(lv_event_t * e);
lv_obj_t * ui_btnWifiScannerScan;
lv_obj_t * ui_lblWifiScannerScan;
lv_obj_t * ui_txtWifiScanNetsFound;
lv_obj_t * ui_lblWifiScanNetsFound;
void ui_event_ddlWifiSSID(lv_event_t * e);
lv_obj_t * ui_ddlWifiSSID;
void ui_event_btnWifiScannerJoin(lv_event_t * e);
lv_obj_t * ui_btnWifiScannerJoin;
lv_obj_t * ui_lblWifiScannerJoin;
lv_obj_t * ui_WifiApps;
void ui_event_btnWifiBack(lv_event_t * e);
lv_obj_t * ui_btnWifiBack;
lv_obj_t * ui_lblWifiBack;


// SCREEN: ui_scrRCSWMain
void ui_scrRCSWMain_screen_init(void);
lv_obj_t * ui_scrRCSWMain;
lv_obj_t * ui_lblRCSWMain;
lv_obj_t * ui_tabRCSWApps;
lv_obj_t * ui_TenPole;
void ui_event_btnTenPoleTxOn(lv_event_t * e);
lv_obj_t * ui_btnTenPoleTxOn;
lv_obj_t * ui_lblTenPoleTxOn;
void ui_event_btnTenPoleTxOff(lv_event_t * e);
lv_obj_t * ui_btnTenPoleTxOff;
lv_obj_t * ui_lblTenPoleTxOff;
void ui_event_TenPoleSW0(lv_event_t * e);
lv_obj_t * ui_TenPoleSW0;
void ui_event_TenPoleSW1(lv_event_t * e);
lv_obj_t * ui_TenPoleSW1;
void ui_event_TenPoleSW2(lv_event_t * e);
lv_obj_t * ui_TenPoleSW2;
void ui_event_TenPoleSW3(lv_event_t * e);
lv_obj_t * ui_TenPoleSW3;
void ui_event_TenPoleSW4(lv_event_t * e);
lv_obj_t * ui_TenPoleSW4;
void ui_event_TenPoleSW5(lv_event_t * e);
lv_obj_t * ui_TenPoleSW5;
void ui_event_TenPoleSW6(lv_event_t * e);
lv_obj_t * ui_TenPoleSW6;
void ui_event_TenPoleSW7(lv_event_t * e);
lv_obj_t * ui_TenPoleSW7;
void ui_event_TenPoleSW8(lv_event_t * e);
lv_obj_t * ui_TenPoleSW8;
void ui_event_TenPoleSW9(lv_event_t * e);
lv_obj_t * ui_TenPoleSW9;
lv_obj_t * ui_lblBit0;
lv_obj_t * ui_lblBit1;
lv_obj_t * ui_lblBit2;
lv_obj_t * ui_lblBit3;
lv_obj_t * ui_lblBit4;
lv_obj_t * ui_lblBit5;
lv_obj_t * ui_lblBit6;
lv_obj_t * ui_lblBit7;
lv_obj_t * ui_lblBit8;
lv_obj_t * ui_lblBit9;
lv_obj_t * ui_ddlTenProto;
void ui_event_txt10PoleFreq(lv_event_t * e);
lv_obj_t * ui_txt10PoleFreq;
lv_obj_t * ui_lblRCSWStatus;
lv_obj_t * ui_NEW;
void ui_event_btnRCSWBack(lv_event_t * e);
lv_obj_t * ui_btnRCSWBack;
lv_obj_t * ui_lblRCSWBack;
lv_obj_t * ui_panelRCSWFreqKeyboard;
lv_obj_t * ui_lblRCSWFreqKeyboardValueUnits;
lv_obj_t * ui_lblRCSWFreqKeyboardTitle;


// SCREEN: ui_scrCC1101Stuff
void ui_scrCC1101Stuff_screen_init(void);
lv_obj_t * ui_scrCC1101Stuff;
lv_obj_t * ui_lblCC1101Scan;
void ui_event_tabCC1101Stuff(lv_event_t * e);
lv_obj_t * ui_tabCC1101Stuff;
lv_obj_t * ui_Scanner;
lv_obj_t * ui_txtScannerData;
void ui_event_txtScanStopFq(lv_event_t * e);
lv_obj_t * ui_txtScanStopFq;
void ui_event_txtScanStartFq(lv_event_t * e);
lv_obj_t * ui_txtScanStartFq;
lv_obj_t * ui_lblScanStartFq;
lv_obj_t * ui_lblScanStopFq;
void ui_event_swScannerOn(lv_event_t * e);
lv_obj_t * ui_swScannerOn;
lv_obj_t * ui_lblScanEnable;
void ui_event_btnScannerClear(lv_event_t * e);
lv_obj_t * ui_btnScannerClear;
lv_obj_t * ui_lblScannerClear;
void ui_event_sldThreshold(lv_event_t * e);
lv_obj_t * ui_sldThreshold;
lv_obj_t * ui_lblSldThreshold;
lv_obj_t * ui_lblThreshold;
void ui_event_ddl1101ScanPreset(lv_event_t * e);
lv_obj_t * ui_ddl1101ScanPreset;
lv_obj_t * ui_lbl1101ScanPreset;
lv_obj_t * ui_chkScanPresets;
lv_obj_t * ui_Generator;
void ui_event_txt1101GenFreq(lv_event_t * e);
lv_obj_t * ui_txt1101GenFreq;
void ui_event_swGenEnable(lv_event_t * e);
lv_obj_t * ui_swGenEnable;
lv_obj_t * ui_lblGenEnable;
void ui_event_ddl1101GenPreset(lv_event_t * e);
lv_obj_t * ui_ddl1101GenPreset;
lv_obj_t * ui_lbl1101GenPreset;
lv_obj_t * ui_RecPlayback;
lv_obj_t * ui_indRed;
lv_obj_t * ui_indGreen;
void ui_event_btnCapture(lv_event_t * e);
lv_obj_t * ui_btnCapture;
lv_obj_t * ui_lblCapture;
void ui_event_btnPlayback(lv_event_t * e);
lv_obj_t * ui_btnPlayback;
void ui_event_lblPlayback(lv_event_t * e);
lv_obj_t * ui_lblPlayback;
lv_obj_t * ui_lblRecPlayStatus;
void ui_event_txtRecPlayFq(lv_event_t * e);
lv_obj_t * ui_txtRecPlayFq;
void ui_event_Preset(lv_event_t * e);
lv_obj_t * ui_Preset;
lv_obj_t * ui_lblRadioPreset;
lv_obj_t * ui_btnSave;
lv_obj_t * ui_lblSave;
lv_obj_t * ui_txtRawData;
lv_obj_t * ui_Config;
void ui_event_arcScanBW(lv_event_t * e);
lv_obj_t * ui_arcScanBW;
lv_obj_t * ui_lblRXBWArc;
lv_obj_t * ui_lblRXBWKhz;
void ui_event_ddlCC1101ModType(lv_event_t * e);
lv_obj_t * ui_ddlCC1101ModType;
lv_obj_t * ui_lblCC1101ModType;
void ui_event_ddlCC1101PktFormat(lv_event_t * e);
lv_obj_t * ui_ddlCC1101PktFormat;
lv_obj_t * ui_lblCC1101PktFormat;
lv_obj_t * ui_lblScannerBW;
void ui_event_Config1101Preset(lv_event_t * e);
lv_obj_t * ui_Config1101Preset;
lv_obj_t * ui_lblCC1101ModType2;
void ui_event_arcDeviation(lv_event_t * e);
lv_obj_t * ui_arcDeviation;
lv_obj_t * ui_lblDeviation;
lv_obj_t * ui_lblDeviationKhz;
lv_obj_t * ui_lblScannerBW1;
void ui_event_btnScanBack(lv_event_t * e);
lv_obj_t * ui_btnScanBack;
lv_obj_t * ui_lblScanBack;
lv_obj_t * ui_panelCC1101StuffFreqKeyboard;
lv_obj_t * ui_lblCC1101StuffFreqKeyboardValueUnits;
lv_obj_t * ui_lblCC1101StuffFreqKeyboardTitle;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_splashbkgnd[1] = {&ui_img_splashbkgnd2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_scrSplash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_scrMain_screen_init);
    }
}
void ui_event_btnMain1101(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_load_screen_scan(e);
    }
}
void ui_event_btnMainRCSW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_load_screen_rcsw(e);
    }
}
void ui_event_btnMainFlipper(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_load_screen_flipper(e);
    }
}
void ui_event_btnMainPlayMp3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_play_audio_test(e);
    }
}
void ui_event_btnMainStopMp3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_stop_audio(e);
    }
}
void ui_event_sliderMainVolumeMp3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_lblMainVolumeMp3, target, "Volume: ", "");
        event_set_volume_audio(e);
    }
}
void ui_event_btnMainSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_load_screen_settings(e);
    }
}
void ui_event_btnMainWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_load_screen_wifi_apps(e);
    }
}
void ui_event_btnMainProtAna(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_load_screen_protocol_analyzer(e);
    }
}
void ui_event_btnProtAnaCncl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_exit_protocol_analyzer(e);
    }
}
void ui_event_btnProtAnaClear(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_clear_protocol_analyzer(e);
    }
}
void ui_event_swtProtAnaRxEn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_start_stop_protocol_analyzer(e);
    }
}
void ui_event_txtMainFreq(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        event_keyboard_protocol_analyzer(e);
    }
    if(event_code == LV_EVENT_READY) {
        event_keyboard_protocol_analyzer(e);
    }
}
void ui_event_btnProtanaReplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_replay_protocol_analyzer(e);
    }
}
void ui_event_ProtanaPreset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_set_preset_analyzer(e);
    }
}
void ui_event_btnPresetsBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_scrMain_screen_init);
    }
}
void ui_event_ddPresetsFolder(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_refresh_flipper_file(e);
    }
}
void ui_event_ddPresetsFile(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_select_flipper_file(e);
    }
}
void ui_event_btnPresetTx(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_send_flipper_file(e);
    }
}
void ui_event_btnPresetTesla(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_send_tesla(e);
    }
}
void ui_event_btnSettingsOTA(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_enable_ota_device(e);
    }
}
void ui_event_btnSettingsBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_scrMain_screen_init);
    }
}
void ui_event_btnSettingsSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_save_settings_device(e);
    }
}
void ui_event_btnRotate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_rotate_device(e);
    }
}
void ui_event_sldBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_set_brightness_device(e);
    }
}
void ui_event_btnAbout(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrSplash, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_scrSplash_screen_init);
    }
}
void ui_event_btnRestart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_restart_device(e);
    }
}
void ui_event_kybdEntry(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_kybdEntry,  ui_txtKybdEntry);
    }
}
void ui_event_btnWifiScannerScan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_start_wifi_scan(e);
    }
}
void ui_event_ddlWifiSSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_refresh_wifi(e);
    }
}
void ui_event_btnWifiScannerJoin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_join_wifi(e);
    }
}
void ui_event_btnWifiBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_exit_wifi_screen(e);
    }
}
void ui_event_btnTenPoleTxOn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_rc_switch_send_on(e);
    }
}
void ui_event_btnTenPoleTxOff(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_rc_switch_send_off(e);
    }
}
void ui_event_TenPoleSW0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit0, _UI_LABEL_PROPERTY_TEXT, "1");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit0, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}
void ui_event_TenPoleSW1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit1, _UI_LABEL_PROPERTY_TEXT, "1");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit1, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}
void ui_event_TenPoleSW2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit2, _UI_LABEL_PROPERTY_TEXT, "1");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit2, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}
void ui_event_TenPoleSW3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit3, _UI_LABEL_PROPERTY_TEXT, "1");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit3, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}
void ui_event_TenPoleSW4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit4, _UI_LABEL_PROPERTY_TEXT, "1");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit4, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}
void ui_event_TenPoleSW5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit5, _UI_LABEL_PROPERTY_TEXT, "1");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit5, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}
void ui_event_TenPoleSW6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit6, _UI_LABEL_PROPERTY_TEXT, "1");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit6, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}
void ui_event_TenPoleSW7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit7, _UI_LABEL_PROPERTY_TEXT, "1");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit7, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}
void ui_event_TenPoleSW8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit8, _UI_LABEL_PROPERTY_TEXT, "1");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit8, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}
void ui_event_TenPoleSW9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit9, _UI_LABEL_PROPERTY_TEXT, "1");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBit9, _UI_LABEL_PROPERTY_TEXT, "0");
    }
}
void ui_event_txt10PoleFreq(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        event_keyboard_rcsw(e);
    }
    if(event_code == LV_EVENT_READY) {
        event_keyboard_rcsw(e);
    }
}
void ui_event_btnRCSWBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_scrMain_screen_init);
    }
}
void ui_event_tabCC1101Stuff(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_tab_change_cc1101_stuff(e);
    }
}
void ui_event_txtScanStopFq(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        event_keyboard_scanner_stop(e);
    }
    if(event_code == LV_EVENT_READY) {
        event_keyboard_scanner_stop(e);
    }
}
void ui_event_txtScanStartFq(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        event_keyboard_scanner_start(e);
    }
    if(event_code == LV_EVENT_READY) {
        event_keyboard_scanner_start(e);
    }
}
void ui_event_swScannerOn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_start_stop_scanner(e);
    }
}
void ui_event_btnScannerClear(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_clear_scanner(e);
    }
}
void ui_event_sldThreshold(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_lblThreshold, target, "", "");
    }
}
void ui_event_ddl1101ScanPreset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_set_scan_preset_freq(e);
    }
}
void ui_event_txt1101GenFreq(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        event_keyboard_packet_generator(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        event_keyboard_packet_generator(e);
    }
    if(event_code == LV_EVENT_READY) {
        event_keyboard_packet_generator(e);
    }
}
void ui_event_swGenEnable(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_start_stop_packet_gen(e);
    }
}
void ui_event_ddl1101GenPreset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_set_gen_preset_freq(e);
    }
}
void ui_event_btnCapture(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_capture_rec_play(e);
    }
}
void ui_event_btnPlayback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_playback_rec_play(e);
    }
}
void ui_event_lblPlayback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_playback_rec_play(e);
    }
}
void ui_event_txtRecPlayFq(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        event_keyboard_rec_play(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        event_keyboard_rec_play(e);
    }
    if(event_code == LV_EVENT_READY) {
        event_keyboard_rec_play(e);
    }
}
void ui_event_Preset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_set_preset_rec_play(e);
    }
}
void ui_event_arcScanBW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_lblRXBWArc, target, "", "");
    }
}
void ui_event_ddlCC1101ModType(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_set_modulation(e);
    }
}
void ui_event_ddlCC1101PktFormat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_set_packet_format(e);
    }
}
void ui_event_Config1101Preset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_set_preset(e);
    }
}
void ui_event_arcDeviation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_lblDeviation, target, "", "");
    }
}
void ui_event_btnScanBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        event_exit_cc1101_stuff(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrSplash_screen_init();
    ui_scrMain_screen_init();
    ui_scrProtAna_screen_init();
    ui_scrPresets_screen_init();
    ui_scrSettings_screen_init();
    ui_scrWifiApps_screen_init();
    ui_scrRCSWMain_screen_init();
    ui_scrCC1101Stuff_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrSplash);
}
