// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: WaveSentinel

#ifndef _WAVESENTINEL_UI_H
#define _WAVESENTINEL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_scrSplash
void ui_scrSplash_screen_init(void);
void ui_event_scrSplash(lv_event_t * e);
extern lv_obj_t * ui_scrSplash;
extern lv_obj_t * ui_lblSplash;
extern lv_obj_t * ui_lblSplashStatus;
extern lv_obj_t * ui_lblVersion;
// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);
extern lv_obj_t * ui_scrMain;
void ui_event_btnMain1101(lv_event_t * e);
extern lv_obj_t * ui_btnMain1101;
extern lv_obj_t * ui_lblMain1101;
void ui_event_btnMainRCSW(lv_event_t * e);
extern lv_obj_t * ui_btnMainRCSW;
extern lv_obj_t * ui_lblMainRCSW;
void ui_event_btnMainFlipper(lv_event_t * e);
extern lv_obj_t * ui_btnMainFlipper;
extern lv_obj_t * ui_imgMainFlipper;
extern lv_obj_t * ui_btnMainRecPlay;
void ui_event_btnMainPlayMp3(lv_event_t * e);
extern lv_obj_t * ui_btnMainPlayMp3;
extern lv_obj_t * ui_lblMainPlayMp3;
void ui_event_btnMainStopMp3(lv_event_t * e);
extern lv_obj_t * ui_btnMainStopMp3;
extern lv_obj_t * ui_lblMainStopMp3;
extern lv_obj_t * ui_lblMainVolumeMp3;
void ui_event_sliderMainVolumeMp3(lv_event_t * e);
extern lv_obj_t * ui_sliderMainVolumeMp3;
extern lv_obj_t * ui_btnMainUnmapped7;
void ui_event_btnMainSettings(lv_event_t * e);
extern lv_obj_t * ui_btnMainSettings;
void ui_event_btnMainWifi(lv_event_t * e);
extern lv_obj_t * ui_btnMainWifi;
extern lv_obj_t * ui_imgMainWifi;
void ui_event_btnMainProtAna(lv_event_t * e);
extern lv_obj_t * ui_btnMainProtAna;
extern lv_obj_t * ui_imgMainProtana;
extern lv_obj_t * ui_lblMainProtAna;
extern lv_obj_t * ui_lblMainStatus;
extern lv_obj_t * ui_lblMainSettings;
extern lv_obj_t * ui_lblMainMenuTitle;
// SCREEN: ui_scrProtAna
void ui_scrProtAna_screen_init(void);
extern lv_obj_t * ui_scrProtAna;
extern lv_obj_t * ui_lblProtAnalyzerTitle;
extern lv_obj_t * ui_txtProtAnaResults;
void ui_event_btnProtAnaCncl(lv_event_t * e);
extern lv_obj_t * ui_btnProtAnaCncl;
extern lv_obj_t * ui_lblProtAnaCncl;
void ui_event_btnProtAnaClear(lv_event_t * e);
extern lv_obj_t * ui_btnProtAnaClear;
extern lv_obj_t * ui_lblProtAnaClear;
void ui_event_swtProtAnaRxEn(lv_event_t * e);
extern lv_obj_t * ui_swtProtAnaRxEn;
extern lv_obj_t * ui_lblProtAnaRXEn;
extern lv_obj_t * ui_lblMainFreq;
void ui_event_txtMainFreq(lv_event_t * e);
extern lv_obj_t * ui_txtMainFreq;
extern lv_obj_t * ui_lblProtAnaReceived;
extern lv_obj_t * ui_lblProtAnaBitLength;
extern lv_obj_t * ui_txtProtAnaReceived;
extern lv_obj_t * ui_txtProtAnaBitLength;
extern lv_obj_t * ui_lblProtAnaBinary;
extern lv_obj_t * ui_txtProtAnaBinary;
extern lv_obj_t * ui_lblProtAnaPulsLen;
extern lv_obj_t * ui_txtProtAnaPulsLen;
extern lv_obj_t * ui_lblProtAnaTriState;
extern lv_obj_t * ui_txtProtAnaProtAnaTriState;
extern lv_obj_t * ui_txtProtAnaProtocol;
extern lv_obj_t * ui_lblProtAnaProtocol;
void ui_event_btnProtanaReplay(lv_event_t * e);
extern lv_obj_t * ui_btnProtanaReplay;
extern lv_obj_t * ui_lblProtanaReplay;
extern lv_obj_t * ui_lblProtAnaPreset;
void ui_event_ProtanaPreset(lv_event_t * e);
extern lv_obj_t * ui_ProtanaPreset;
extern lv_obj_t * ui_panelProtAnaFreqKeyboard;
extern lv_obj_t * ui_lblProtAnaFreqKeyboardValueUnits;
extern lv_obj_t * ui_lblProtAnaFreqKeyboardTitle;
// SCREEN: ui_scrPresets
void ui_scrPresets_screen_init(void);
extern lv_obj_t * ui_scrPresets;
extern lv_obj_t * ui_lblPresetsTitle;
extern lv_obj_t * ui_lblPresetsFolder;
extern lv_obj_t * ui_lblPresetsFile;
void ui_event_btnPresetsBack(lv_event_t * e);
extern lv_obj_t * ui_btnPresetsBack;
extern lv_obj_t * ui_lblPresetsBack;
extern lv_obj_t * ui_lblPresetsStatus;
void ui_event_ddPresetsFolder(lv_event_t * e);
extern lv_obj_t * ui_ddPresetsFolder;
void ui_event_ddPresetsFile(lv_event_t * e);
extern lv_obj_t * ui_ddPresetsFile;
void ui_event_btnPresetTx(lv_event_t * e);
extern lv_obj_t * ui_btnPresetTx;
extern lv_obj_t * ui_lblPresetTx;
void ui_event_btnPresetTesla(lv_event_t * e);
extern lv_obj_t * ui_btnPresetTesla;
extern lv_obj_t * ui_lblPresetTesla;
// SCREEN: ui_scrSettings
void ui_scrSettings_screen_init(void);
extern lv_obj_t * ui_scrSettings;
extern lv_obj_t * ui_lblSettingsTitle;
void ui_event_btnSettingsOTA(lv_event_t * e);
extern lv_obj_t * ui_btnSettingsOTA;
extern lv_obj_t * ui_lblSettingsOTA;
extern lv_obj_t * ui_lblSettingsStatus;
void ui_event_btnSettingsBack(lv_event_t * e);
extern lv_obj_t * ui_btnSettingsBack;
extern lv_obj_t * ui_lblSettingsBack;
extern lv_obj_t * ui_lblSettingsWifiIP;
extern lv_obj_t * ui_lblSettingsIPAddr;
extern lv_obj_t * ui_lblSettingsInfo;
extern lv_obj_t * ui_barProgress;
extern lv_obj_t * ui_swSettingsWifiMode;
extern lv_obj_t * ui_lblSettingsWifiSSID;
extern lv_obj_t * ui_txtSettingsWifiSSID;
extern lv_obj_t * ui_lblSettingsWifiKey;
extern lv_obj_t * ui_txtSettingsWifiKey;
extern lv_obj_t * ui_lblSettingsWifiMode;
extern lv_obj_t * ui_lblSettingsWifiModeAP;
extern lv_obj_t * ui_lblSettingsWifiModeSTA;
void ui_event_btnSettingsSave(lv_event_t * e);
extern lv_obj_t * ui_btnSettingsSave;
extern lv_obj_t * ui_lblSettingsSave;
void ui_event_btnRotate(lv_event_t * e);
extern lv_obj_t * ui_btnRotate;
extern lv_obj_t * ui_lblRotate;
void ui_event_sldBrightness(lv_event_t * e);
extern lv_obj_t * ui_sldBrightness;
extern lv_obj_t * ui_Label2;
void ui_event_btnAbout(lv_event_t * e);
extern lv_obj_t * ui_btnAbout;
extern lv_obj_t * ui_lblAbout;
void ui_event_btnRestart(lv_event_t * e);
extern lv_obj_t * ui_btnRestart;
extern lv_obj_t * ui_lblRestart;
extern lv_obj_t * ui_panelWiFiKeyboard;
extern lv_obj_t * ui_txtKybdEntry;
void ui_event_kybdEntry(lv_event_t * e);
extern lv_obj_t * ui_kybdEntry;
extern lv_obj_t * ui_lblKybdInstruction;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_scrWifiApps
void ui_scrWifiApps_screen_init(void);
extern lv_obj_t * ui_scrWifiApps;
extern lv_obj_t * ui_lblWifiMain;
extern lv_obj_t * ui_tabWifiApps;
extern lv_obj_t * ui_WifiScan;
void ui_event_btnWifiScannerScan(lv_event_t * e);
extern lv_obj_t * ui_btnWifiScannerScan;
extern lv_obj_t * ui_lblWifiScannerScan;
extern lv_obj_t * ui_txtWifiScanNetsFound;
extern lv_obj_t * ui_lblWifiScanNetsFound;
void ui_event_ddlWifiSSID(lv_event_t * e);
extern lv_obj_t * ui_ddlWifiSSID;
void ui_event_btnWifiScannerJoin(lv_event_t * e);
extern lv_obj_t * ui_btnWifiScannerJoin;
extern lv_obj_t * ui_lblWifiScannerJoin;
extern lv_obj_t * ui_WifiApps;
void ui_event_btnWifiBack(lv_event_t * e);
extern lv_obj_t * ui_btnWifiBack;
extern lv_obj_t * ui_lblWifiBack;
// SCREEN: ui_scrRCSWMain
void ui_scrRCSWMain_screen_init(void);
extern lv_obj_t * ui_scrRCSWMain;
extern lv_obj_t * ui_lblRCSWMain;
extern lv_obj_t * ui_tabRCSWApps;
extern lv_obj_t * ui_TenPole;
void ui_event_btnTenPoleTxOn(lv_event_t * e);
extern lv_obj_t * ui_btnTenPoleTxOn;
extern lv_obj_t * ui_lblTenPoleTxOn;
void ui_event_btnTenPoleTxOff(lv_event_t * e);
extern lv_obj_t * ui_btnTenPoleTxOff;
extern lv_obj_t * ui_lblTenPoleTxOff;
void ui_event_TenPoleSW0(lv_event_t * e);
extern lv_obj_t * ui_TenPoleSW0;
void ui_event_TenPoleSW1(lv_event_t * e);
extern lv_obj_t * ui_TenPoleSW1;
void ui_event_TenPoleSW2(lv_event_t * e);
extern lv_obj_t * ui_TenPoleSW2;
void ui_event_TenPoleSW3(lv_event_t * e);
extern lv_obj_t * ui_TenPoleSW3;
void ui_event_TenPoleSW4(lv_event_t * e);
extern lv_obj_t * ui_TenPoleSW4;
void ui_event_TenPoleSW5(lv_event_t * e);
extern lv_obj_t * ui_TenPoleSW5;
void ui_event_TenPoleSW6(lv_event_t * e);
extern lv_obj_t * ui_TenPoleSW6;
void ui_event_TenPoleSW7(lv_event_t * e);
extern lv_obj_t * ui_TenPoleSW7;
void ui_event_TenPoleSW8(lv_event_t * e);
extern lv_obj_t * ui_TenPoleSW8;
void ui_event_TenPoleSW9(lv_event_t * e);
extern lv_obj_t * ui_TenPoleSW9;
extern lv_obj_t * ui_lblBit0;
extern lv_obj_t * ui_lblBit1;
extern lv_obj_t * ui_lblBit2;
extern lv_obj_t * ui_lblBit3;
extern lv_obj_t * ui_lblBit4;
extern lv_obj_t * ui_lblBit5;
extern lv_obj_t * ui_lblBit6;
extern lv_obj_t * ui_lblBit7;
extern lv_obj_t * ui_lblBit8;
extern lv_obj_t * ui_lblBit9;
extern lv_obj_t * ui_ddlTenProto;
void ui_event_txt10PoleFreq(lv_event_t * e);
extern lv_obj_t * ui_txt10PoleFreq;
extern lv_obj_t * ui_lblRCSWStatus;
extern lv_obj_t * ui_NEW;
void ui_event_btnRCSWBack(lv_event_t * e);
extern lv_obj_t * ui_btnRCSWBack;
extern lv_obj_t * ui_lblRCSWBack;
extern lv_obj_t * ui_panelRCSWFreqKeyboard;
extern lv_obj_t * ui_lblRCSWFreqKeyboardValueUnits;
extern lv_obj_t * ui_lblRCSWFreqKeyboardTitle;
// SCREEN: ui_scrCC1101Stuff
void ui_scrCC1101Stuff_screen_init(void);
extern lv_obj_t * ui_scrCC1101Stuff;
extern lv_obj_t * ui_lblCC1101Scan;
void ui_event_tabCC1101Stuff(lv_event_t * e);
extern lv_obj_t * ui_tabCC1101Stuff;
extern lv_obj_t * ui_Scanner;
extern lv_obj_t * ui_txtScannerData;
void ui_event_txtScanStopFq(lv_event_t * e);
extern lv_obj_t * ui_txtScanStopFq;
void ui_event_txtScanStartFq(lv_event_t * e);
extern lv_obj_t * ui_txtScanStartFq;
extern lv_obj_t * ui_lblScanStartFq;
extern lv_obj_t * ui_lblScanStopFq;
void ui_event_swScannerOn(lv_event_t * e);
extern lv_obj_t * ui_swScannerOn;
extern lv_obj_t * ui_lblScanEnable;
void ui_event_btnScannerClear(lv_event_t * e);
extern lv_obj_t * ui_btnScannerClear;
extern lv_obj_t * ui_lblScannerClear;
void ui_event_sldThreshold(lv_event_t * e);
extern lv_obj_t * ui_sldThreshold;
extern lv_obj_t * ui_lblSldThreshold;
extern lv_obj_t * ui_lblThreshold;
void ui_event_ddl1101ScanPreset(lv_event_t * e);
extern lv_obj_t * ui_ddl1101ScanPreset;
extern lv_obj_t * ui_lbl1101ScanPreset;
extern lv_obj_t * ui_chkScanPresets;
extern lv_obj_t * ui_Generator;
void ui_event_txt1101GenFreq(lv_event_t * e);
extern lv_obj_t * ui_txt1101GenFreq;
void ui_event_swGenEnable(lv_event_t * e);
extern lv_obj_t * ui_swGenEnable;
extern lv_obj_t * ui_lblGenEnable;
void ui_event_ddl1101GenPreset(lv_event_t * e);
extern lv_obj_t * ui_ddl1101GenPreset;
extern lv_obj_t * ui_lbl1101GenPreset;
extern lv_obj_t * ui_RecPlayback;
extern lv_obj_t * ui_indRed;
extern lv_obj_t * ui_indGreen;
void ui_event_btnCapture(lv_event_t * e);
extern lv_obj_t * ui_btnCapture;
extern lv_obj_t * ui_lblCapture;
void ui_event_btnPlayback(lv_event_t * e);
extern lv_obj_t * ui_btnPlayback;
void ui_event_lblPlayback(lv_event_t * e);
extern lv_obj_t * ui_lblPlayback;
extern lv_obj_t * ui_lblRecPlayStatus;
void ui_event_txtRecPlayFq(lv_event_t * e);
extern lv_obj_t * ui_txtRecPlayFq;
void ui_event_Preset(lv_event_t * e);
extern lv_obj_t * ui_Preset;
extern lv_obj_t * ui_lblRadioPreset;
extern lv_obj_t * ui_btnSave;
extern lv_obj_t * ui_lblSave;
extern lv_obj_t * ui_txtRawData;
extern lv_obj_t * ui_Config;
void ui_event_arcScanBW(lv_event_t * e);
extern lv_obj_t * ui_arcScanBW;
extern lv_obj_t * ui_lblRXBWArc;
extern lv_obj_t * ui_lblRXBWKhz;
void ui_event_ddlCC1101ModType(lv_event_t * e);
extern lv_obj_t * ui_ddlCC1101ModType;
extern lv_obj_t * ui_lblCC1101ModType;
void ui_event_ddlCC1101PktFormat(lv_event_t * e);
extern lv_obj_t * ui_ddlCC1101PktFormat;
extern lv_obj_t * ui_lblCC1101PktFormat;
extern lv_obj_t * ui_lblScannerBW;
void ui_event_Config1101Preset(lv_event_t * e);
extern lv_obj_t * ui_Config1101Preset;
extern lv_obj_t * ui_lblCC1101ModType2;
void ui_event_arcDeviation(lv_event_t * e);
extern lv_obj_t * ui_arcDeviation;
extern lv_obj_t * ui_lblDeviation;
extern lv_obj_t * ui_lblDeviationKhz;
extern lv_obj_t * ui_lblScannerBW1;
void ui_event_btnScanBack(lv_event_t * e);
extern lv_obj_t * ui_btnScanBack;
extern lv_obj_t * ui_lblScanBack;
extern lv_obj_t * ui_panelCC1101StuffFreqKeyboard;
extern lv_obj_t * ui_lblCC1101StuffFreqKeyboardValueUnits;
extern lv_obj_t * ui_lblCC1101StuffFreqKeyboardTitle;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_wavesentinelnew_png);    // assets/WaveSentinelNew.png
LV_IMG_DECLARE(ui_img_blankpgbkgnd_png);    // assets/BlankPgBkgnd.png
LV_IMG_DECLARE(ui_img_flippericon_png);    // assets/FlipperIcon.png
LV_IMG_DECLARE(ui_img_wifilogo_png);    // assets/WifiLogo.png
LV_IMG_DECLARE(ui_img_analyzericon_png);    // assets/AnalyzerIcon.png
LV_IMG_DECLARE(ui_img_needle_png);    // assets/Needle.png
LV_IMG_DECLARE(ui_img_txind_png);    // assets/TXInd.png
LV_IMG_DECLARE(ui_img_rxind_png);    // assets/RXInd.png
LV_IMG_DECLARE(ui_img_splashbkgnd2_png);    // assets/SplashBkgnd2.png



LV_FONT_DECLARE(ui_font_LCD20at8BPP);
LV_FONT_DECLARE(ui_font_LCD22at8BPP);
LV_FONT_DECLARE(ui_font_LCD24at8BPP);
LV_FONT_DECLARE(ui_font_LCD30at8BPP);
LV_FONT_DECLARE(ui_font_Verdana11);
LV_FONT_DECLARE(ui_font_Verdana12);
LV_FONT_DECLARE(ui_font_Verdana14);
LV_FONT_DECLARE(ui_font_Verdana16);
LV_FONT_DECLARE(ui_font_Verdana18);
LV_FONT_DECLARE(ui_font_Verdana24);
LV_FONT_DECLARE(ui_font_Verdana8);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
