// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: WaveSentinel

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void event_load_screen_scan(lv_event_t * e);
void event_load_screen_rcsw(lv_event_t * e);
void event_load_screen_flipper(lv_event_t * e);
void event_play_audio_test(lv_event_t * e);
void event_stop_audio(lv_event_t * e);
void event_set_volume_audio(lv_event_t * e);
void event_load_screen_settings(lv_event_t * e);
void event_load_screen_wifi_apps(lv_event_t * e);
void event_load_screen_protocol_analyzer(lv_event_t * e);
void event_exit_protocol_analyzer(lv_event_t * e);
void event_clear_protocol_analyzer(lv_event_t * e);
void event_start_stop_protocol_analyzer(lv_event_t * e);
void event_keyboard_protocol_analyzer(lv_event_t * e);
void event_replay_protocol_analyzer(lv_event_t * e);
void event_set_preset_analyzer(lv_event_t * e);
void event_refresh_flipper_file(lv_event_t * e);
void event_select_flipper_file(lv_event_t * e);
void event_send_flipper_file(lv_event_t * e);
void event_send_tesla(lv_event_t * e);
void event_enable_ota_device(lv_event_t * e);
void event_save_settings_device(lv_event_t * e);
void event_rotate_device(lv_event_t * e);
void event_set_brightness_device(lv_event_t * e);
void event_restart_device(lv_event_t * e);
void event_start_wifi_scan(lv_event_t * e);
void event_refresh_wifi(lv_event_t * e);
void event_join_wifi(lv_event_t * e);
void event_exit_wifi_screen(lv_event_t * e);
void event_rc_switch_send_on(lv_event_t * e);
void event_rc_switch_send_off(lv_event_t * e);
void event_keyboard_rcsw(lv_event_t * e);
void event_tab_change_cc1101_stuff(lv_event_t * e);
void event_keyboard_scanner_stop(lv_event_t * e);
void event_keyboard_scanner_start(lv_event_t * e);
void event_start_stop_scanner(lv_event_t * e);
void event_clear_scanner(lv_event_t * e);
void event_set_scan_preset_freq(lv_event_t * e);
void event_keyboard_packet_generator(lv_event_t * e);
void event_start_stop_packet_gen(lv_event_t * e);
void event_set_gen_preset_freq(lv_event_t * e);
void event_capture_rec_play(lv_event_t * e);
void event_playback_rec_play(lv_event_t * e);
void event_keyboard_rec_play(lv_event_t * e);
void event_set_preset_rec_play(lv_event_t * e);
void event_set_modulation(lv_event_t * e);
void event_set_packet_format(lv_event_t * e);
void event_set_preset(lv_event_t * e);
void event_exit_cc1101_stuff(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
